### ISSUE TITLE
Democles update-sites unavailable

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#1]
@gervarro Hi Greg,

I am having trouble accessing the Democles update-sites. When I try to load the list of available software, I get this error:
org.eclipse.equinox.p2.core.ProvisionException
Unable to connect to repository http://gervarro.org/democles/integration-0.5.0/content.xml

The exact URLs I try to access are:
http://gervarro.org/democles/integration-0.5.0/
http://gervarro.org/democles/advanced/integration-0.5.0/

Since Tony was able to reproduce this error, there might be something wrong with the setup of the update-sites (or with the URLs that we are using, though they worked before). Could you please have a look into that?

Thanks,
Florian

**Comment by gervarro** [comment]
Hi Florian,

I recognized yesterday evening that there were some problems that have nothing to do with the content or the update sites. The content is there, but the site is blocked. I have to clarify the situation with the service provider.

@anthonyanjorin FYI

Bests,
Greg

**Comment by anthonyanjorin** [comment]
@gervarro Hosting on GitHub could be an alternative solution (I think this is what Roland is doing now for eMoflon).

**Comment by gervarro** [comment]
Hi,

the update sites are accessible again. 

@anthonyanjorin I should check whether GitHub can really serve update sites in the way, how I would expect.

Bests,
Greg
