### ISSUE TITLE
RuntimeException from Democles after creating a new edge

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#10]
Hi Greg,

I found a bug where the creation of a new EReference causes a `RuntimeException` in the `handleReferenceAddition()` method of the `NotificationCollector`. The bug occurs in our new test project `testsuite1_ClassInhHier2DB`, namely the test `testsuite1.ClassInhHier2DB.modelgen.SyncInstancesTest`.

I think it might have something to do with EOpposite references, since the reference causing this problem is an EOpposite and our previous meta-models didn't contain any EOpposite references.

If you check out the new project and run the test, you should be able to reproduce the problem. This test is not yet completed, so don't be surprised if it still fails after fixing the problem.

Best regards,
Florian

**Comment by gervarro** [comment]
Hi Florian,

this is caused by an EMF bug (design flaw in the event notification framework). I will try to fix this somehow during the next week.

Best regards,
Greg

**Comment by FStolte** [comment]
@gervarro Just to let you know, we created the new branch `democles-debug` in the repository `https://github.com/eMoflon/emoflon-ibex.git`. From now on, you should check out the test projects from that branch, the master branch is now configured in a way where the tests do not work without having emoflon-ibex installed anymore.

Best regards,
Florian

**Comment by gervarro** [comment]
Bug has been fixed on the advanced update site.

**Comment by anthonyanjorin** [comment]
@FStolte Could you remove the @Ignore annotations and try the tests on master?

**Comment by FStolte** [comment]
All tests affected by this bug pass now.
