### ISSUE TITLE
Using eContainer reference in a pattern to check containment of an object

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#11]
Hi Greg,

I hope you can help me with the following problem:
I want to prevent the application of TGG-rules that create a new containment edge between existing nodes if the target node is already contained somewhere (since this would result in the previous containment to be deleted, which is not desired in the context of TGGs). My first solution did not consider that one node could be contained by different kinds of containment references (in our example, a FamilyMember can be contained in a Family via one of four edges: mother, father, sons or daughters). Since one generally might not know all possible containment edges for an object, I want to create a more generic solution.

Tony told me that you had an idea how to solve this using EObject's `eContainer` which points to the container of the object. At first I assumed that `eContainer` is an `EReference`, in which case I would have easily been able to adapt my current solution. Since `eContainer` is, however, modeled as an operation of EObject, I am not sure how to do this.
Could you please try to explain how I can use `eContainer` to make a pattern that checks if a given EObject is already contained somewhere?

Thanks,
Florian

**Comment by gervarro** [comment]
Hi Florian,

the pattern matcher is extensible, and it is possible to define new constraints (like one that handles containment), and the corresponding operations. Defining new constraints and operations is an easy process, but it involves several steps.

1. New constraints for the EMF specifications (e.g., see the `org.gervarro.democles.specification.emf.constraint.emf.emf` package in the `org.gervarro.democles.specification.emf` module). References and attributes are binary constraints, and a container checking constraint would also be a similar binary constraint.
2. New constraints for the pattern matcher specification (`org.gervarro.democles.constraint.emf` package in the `org.gervarro.democles.emf` module). This is the EMF-independent representation of the same constraint.
3. Runtime operations have to be implemented (sample operations in `org.gervarro.democles.operation.emf` in the `org.gervarro.democles.interpreter.emf` module). Let us take the `BidirectionalOneToOneOperation` class as an example. It supports 3 adornments: to check the existence of a bidirectionally navigable link (Bound, Bound), to traverse the link in forward direction (Bound,Free), and to traverse the link in backward direction (Free, Bound). A container checking operation would be similar to the `UnidirectionalToOneOperation` class, and the actual navigation has to be replaced by the `eContainer()` method invocation.
4. The above-mentioned EMF specification constraints, pattern matcher constraints, and operations have to be added to the pattern matcher during its initial setup (see the type modules, constraint modules and builders in the corresponding packages and modules for steps 1-3, respectively).
5. There is one step that is more complicated, namely, to configure such a newly introduced operation in an incremental setup.

I will prepare these constraints and operations with the next update.

Bests,
Greg

**Comment by gervarro** [comment]
Hi Florian,

the support for such container lookup operation is now available on the update site. You can use the `Container` constraint from the metamodel, which is implemented as `org.gervarro.democles.specification.emf.constraint.emf.emf.Container`. Please note that the constraint has to be used with the following parameterization: `Container(containedObject, container)`.

Bests,
Greg
