### ISSUE TITLE
IndexOutOfBoundsException from seemingly correct patterns

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#15]
Hi Greg,

In the last days I migrated several test projects from the old eMoflon tool to ibex. While doing so, I encountered two new errors which I could not trace back to mistakes in the migration. I also set up a democles-debug branch for you in our new test repository:
https://github.com/eMoflon/emoflon-ibex-tests.git

The relevant tests are in the project `testsuites/BlockCodeAdapter`, in the file `test/testsuite1/BlockCodeAdapter/sync/Batch.java`

When you run the tests, you should get one green test, one with an `AssertionError` from Democles and two with an `IndexOutOfBoundsExceptions` from Democles. The AssertionError could be related to issue #14. However, in this case there are no deletions (as far as I can see it), so I do not know where the Error comes from.

More importantly, the two IndexOutOfBoundsExceptions are very puzzling to me. They are caused by the patterns of the rule `RefinedCreateSrcNodeRule`. This rule refines the rule `SimpleCreateSrcNodeRule` and adds nothing to it. So, apart from a few technical differences in the pattern network, they should have the same patterns. I looked at the patterns and could not see anything wrong with them. Nevertheless, when I remove the rule `RefinedCreateSrcNodeRule`, the exception disappears, even though the rule `SimpleCreateSrcNodeRule` with very similar patterns is still there.

Since that Exception only occurs when not flattening the refinements, it is entirely possible that the error is just caused by a fault in the refinement pattern network. I, however, cannot seem to find a problem with the generated patterns, so it would be very helpful if you could look into this problem.

Thanks,
Florian

**Comment by gervarro** [comment]
It was a bug in the Rete network construction (unrelated to #14) that has been fixed. The fix will be available on the update sites (together with other fixes) next week.

Bests,
Greg

**Comment by gervarro** [comment]
Fixes are available on the 2 update sites.
