### ISSUE TITLE
Join-Failed exception on move to new container

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#27]
Hi Greg,

I have a new example where a join failed exception.

Please see https://github.com/eMoflon/emoflon-ibex-tests/blob/e4949e73a642171fbaf0cb524495a99aa12f6f9e/testsuites/Testsuite_1/test/testsuite1/ClassInhHier2DB/sync/AlignmentBased.java#L210 for the failing test.

Thanks!
Tony

**Comment by gervarro** [comment]
Hi Tony,

An earlier bug fix has not covered all the cases. I re-run the tests, and I found that the `source` and `target` links from the correspondence model objects (e.g., `AttributeToColumn`) are (still ?) not properly removed before the correspondence model object is deleted. This might cause spurious `AssertionFailedErrors` depending on the constructed Rete network structure.

Background: Democles internally generates "fake" events about the removal of a link when the source node is removed from the container hierarchy to ensure a consistent view on the model, however, when the link is there, one Rete node (whose role is to provide access to the model and to minimize the number of duplicated elements (EMF and Democles cache)) still answers true when it is queried about the existence of the link. This is the reason why Democles complains about this inconsistency (model still contains the link, but the event listener already reported its deletion by a "fake" event).

1. If Democles did not internally generate "fake" events, the consistency of the view could not be ensured. EMF events are completely unreliable (or missing) if the source object is not in the containment hierarchy.
2. These "fake" events could be used to actually enforce the required updates in EMF (i.e., the ones I recommended above), but I wanted to avoid this as a default behaviour as a view/listener should only react to changes in the model but not modify the underlying model.
3. Another option would be to always use indexes for each Rete node at the modeling layer, however, this solution would duplicate the original model (i.e., one model in EMF, a copy in the internal Rete cache/index).

While debugging, I found some other strange behaviour. One of them is possibly a bug in Democles (each modelled object is implicitly an `EObject`, which does not appear in any of the metamodels), the other might be a bug in the pattern generation. I am going to check first this latter issue, and open a ticket if this seems to be really a bug.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

I've found one location where we delete src and trg nodes before the corr nodes.
I didn't think this could be problematic but I guess it's generally safer to first delete the corr nodes and all their connections before performing deletion in one or both of the other models.  Maybe this solves the problem you describe above.

In general though I'm a bit worried about the handling you describe.  The following scenario is very common and even normal for TGGs:

1.  I have a triple a <-- c --> b, and a is in some container
2.  I execute a source delta that moves a from its old to a new container (edge deletion and creation)
3.  I expect to be able to reuse the triple a <-- c -->b unchanged and probably just handle the container change of a with a corresponding container change of b (but without destroying the correspondence c).

If I understand correctly Democles would delete the connection between a and c as soon as a is not in a container even if this is just temporary.  Is this correct?  If yes then we need to discuss how to handle this.  Maybe it's not a problem though -- perhaps EMF produces a special "MOVE" event combining the edge deletion and creation operations?  I can't remember right now.

Cheers,
Tony

**Comment by anthonyanjorin** [comment]
Btw:  I just pushed the small fix to the update site.  Could be ready in a few minutes.

**Comment by gervarro** [comment]
Hi Tony,

sorry, but I did not focus properly on the main issues in my last comment. In the concrete failing test case, only the `target` link of the correspondence model object `AttributeToColumn` is deleted, but the `source` link remains in the model, although the `AttributeToColumn` object is removed from the containment hierarchy. Please fix this.

I can formulate the following rules of thumb to support an EMF-based incremental engine:
1. If an object is **temporarily** removed from the containment hierarchy, re-add it as soon as possible (without carrying out any modifications on regular references affecting the containment subtree that is hanging in the air).
2. Delete explicitly all incoming and outgoing regular references of an object before it is **permanently** removed from the containment hierarchy. (The proper explicit deletion could be enforced by some additional helper classes that could rely on the already existing notification processor. Let us discuss the next steps if such a support is needed.)

The scenario you mentioned could be supported if you carry out containment edge insertion directly after its deletion. (The inverse "fake" events are also automatically issued when an object is re-added to the containment hierarchy. The important thing is to avoid the manipulation of incoming and outgoing links of those objects that are hanging in the air.)

Tell me if the above-mentioned two rules block some Ibex functionalities.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

the two rules sound fine.

I've looked at the code carefully and really don't think what you describe is possible.  
I have a suspicion and alternative explanation though:

Our correspondence nodes are all lying directly as multiple root elements in the same correspondence resource so all have no eContainer.  
Can this perhaps be the problem?  What happens during the deletion process is that: (1) the --trg--> edge is explicitly deleted, then (2) the --src--> edge is deleted, then (3) the correspondence node is finally deleted.  

However, after (1) the corr node might appear to be "disconnected" from the containment hierarchy as it never was in one in the first place (it is the root container).  Could this be the problem?

Can you handle this case in your validation or should we just establish a correspondence root container and put all correspondence nodes inside it to avoid this situation?  It doesn't make a big difference for Ibex, but you might want to handle this case (multiple roots in the same resource) in Democles (if my guess is right).  With the join-failed exception it is impossible for me to debug and be certain.

Cheers and thanks,
Tony

**Comment by gervarro** [comment]
Hi Tony,

now I have the impression that I might run some outdated Ibex code. I am going to update the latest fixes in the near future, and afterwards you can experiment yourself. If the `AssertionFailedErrors` still spuriously appear then I will check it again.

The deletion process you described would carry out exactly what I would expect, however, my log files showed that the `source` links were not deleted. (Do not spend time on it. We will see whether the problem is fixed.)

Bests,
Greg

**Comment by anthonyanjorin** [comment]
ok - I should have perhaps mentioned that we delete the source links indirectly by simply invoking EcoreUtil.delete on the correspondence nodes.  But I checked the implementation of EcoreUtil.delete and it does delete all outgoing and even incoming links of the node to be deleted before finally deleting it.

I'll check this as soon you provide the latest fixes.

At least I don't think there is any conceptual problem or mismatch we have to worry about.

**Comment by gervarro** [comment]
Hi Tony,

the latest fixes are available on both update sites.

Best regards,
Greg
