### ISSUE TITLE
Higher memory requirements for more complex networks?

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#28]
Hi Greg,

I am currently testing the performance of the flattened and the refinement pattern networks. So far it is very clear that the refinement pattern network uses far more memory than the flattened pattern network. The main difference is that the refinement network has more invocations / a deeper invocation hierarchy. The individual patterns of the refinement network, however, should be simpler than the flattened ones, rather than more complex.

So, do you think it is to be expected that the refinement network needs more memory, and if yes, can you try to explain why that is?

Thanks,
Florian

**Comment by gervarro** [comment]
Hi Florian,

patterns are considered as independent units, which means that matches are collected independently for each. If I interpret flattened patterns correctly, you probably merge the content of the patterns resulting in a smaller number of patterns. Or do I interpret the flattened network incorrectly?

Bests,
Greg

**Comment by FStolte** [comment]
Actually, while there are slightly more patterns in the refinement version, I don't think that they should affect the performance since they basically are only used for structuring the network.

In the flattened version each TGG rule has its own pattern network. In the refinement version, some rules have pattern networks that invoke patterns of other rules. this increases the number of patterns in the network of one rule, but reduces the amount of constraints in the patterns of that rule.

**Comment by FStolte** [comment]
Here is a sketch of how the Consistency Check network for a rule R1 that refines a rule R2 would look like with both network variants:
![ccstructure](https://user-images.githubusercontent.com/18054693/30484188-eba24ec6-9a29-11e7-97b9-7dcaf42682dd.png)
Orange arrows are positive, blue arrows are negative invocations. The green patterns are the entry points into the networks for R1 and R2, respectively. The white patterns are exactly equal in both pattern networks.
In the flattened version, contents of the SRC, TRG and CORR patterns of R2 are duplicated and put in the corresponding blue patterns of R1. So the patterns R1_SRC, R1_CONTEXT_SRC etc. are smaller than R1+R2_SRC, R1+R2_CONTEXT_SRC...
In the refinement version, the yellow CC_REFINEMENTS patterns are added for each rule (they only contain nodes, and all nodes are used in invocations either to the SRC/TRG/CORR patterns or the CC_REFINEMENT pattern of the super-rule).

Again, the refinement approach requires significantly more memory than the flattened one for most TGGs and I am not sure if this is to be expected with networks like these. I hope you better understand my question with this visualization.

Best Regards,
Florian

**Comment by anthonyanjorin** [comment]
It's also a bit disappointing/surprising that there seems to be no measurable positive effect at all of cleverly reducing the size of individual patterns in the refinement version.
