### ISSUE TITLE
Interrupting democles initialization

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#29]
Hi Greg,

I am currently testing the performance of the flattened and the refinement pattern networks. I have written a framework that automates these tests for various model sizes and TGGs. Naturally, some combinations of sizes and TGGs are very demanding in terms of memory and result in a OutOfMemoryException. Therefore, I tried to put a time limit on every transformation, so that those cases are interrupted before they run out of memory.

Such an interrupt is sometimes necessary during the initialization of Democles (i.e. generation of patterns, registering the models). My problem is that the thread on which i run the initialization will not terminate for some reason when i request it. My code looks roughly like this:

`ExecutorService es = Executors.newSingleThreadExecutor();`
`try {`
`    Future<Long> initDuration = es.submit(() -> initDemocles());`
`long initTime = initDuration.get(20, TimeUnit.SECONDS);`
		   ...
`} catch (TimeoutException e) {`
`    System.out.println("Timeout!");`
`    return null;`
`} finally {`
`    terminate();`
`    es.shutdownNow(); // this should interrupt the thread with democles initialization`
`    es.awaitTermination(1, TimeUnit.HOURS); // however, here i have considerable waiting time and if i leave this out, the thread never terminates for some reason`
`}`

Do you have an idea how I can stop the initialization reliably if it takes too long?

Thanks,
Florian

**Comment by gervarro** [comment]
Hi Florian,

do you want to stop the initialization if it takes too long, or the runtime operation when Java runs out of memory?

Bests,
Greg

**Comment by FStolte** [comment]
Ideally I want to stop when the memory runs out. But the time span from the moment where I can see the memory cap being reached to the point where an actual exception is thrown is several minutes long. Therefore, I just want to give a time limit for the initialization and abort it if it takes too long.

**Comment by anthonyanjorin** [comment]
@FStolte I'm closing this now as we have decided to use launch configurations which can be terminated brutally (as a new VM is started each time).  This should be sufficient for our evaluation framework.
