### ISSUE TITLE
Take container semantics into account when generating multiplicity NACs

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#3]
When handling green edges with a black target node, we have to prevent resetting the container of an existing node (EMF would move this node from its old container to the new one).

Basically there has to be a different handling for normale references ---> and containment references <>---->

**Comment by FStolte** [comment]
I created a method that adds NACs to green containment edges with black target nodes to prevent resetting the containment.
