### ISSUE TITLE
Another Join-Failed exception

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#31]
Hi Greg,

I just committed a new test that causes a JoinFailed exception to the Democles-Debug branch. You can find it under testsuites/Testsuite_1/test/testsuite1/VHDLTGGCodeAdapter/modelgen/ExecutionTest.java

Seems to be a problem with removing matches since the responsible rules are those that have NACs.
Maybe you need to update your Ibex installation for the exception to occur, but I think the test should also work with older versions.

Best Regards,
Florian

**Comment by gervarro** [comment]
Hi Florian,

this might have been caused by the same bug reported in #27. Fixes are available on both update sites. The test is now green.

Best regards,
Greg

**Comment by anthonyanjorin** [comment]
@FStolte Please add this test to master and close this issue if it is green.

**Comment by FStolte** [comment]
Test is green and now integrated into the master branch.
