### ISSUE TITLE
After introducing new patterns, previous patterns cannot be found anymore

### ISSUE THREAD

**Issue by smilicas** [eMoflon/emoflon-ibex-democles#33]
[testProjectSet.zip](https://github.com/eMoflon/emoflon-ibex-democles/files/1474468/testProjectSet.zip)

Hi Greg,

I am working on expanding the pattern network with new patterns to support additional feature called multi-amalgamation for TGGs. Currently I am working with CC patterns, and experienced the strange behavior of the underlying pattern matcher engine: when using regular TGG rules matches are found, but when these rules are complemented with the new rules, not only that these new patterns are not found, but also the old one as well. 
I created a test case in our test suite to demonstrate this behavior. The test is called "testEmptyFamily" in "FamiliesToPersons_MA/cc" package.  In current TC the match for creating family cannot be found. However, if you comment out the complement rule in "FamiliesToPersons_MA" TGG, that complements the "CreateFamily" rule (so, Mother2Female) and run the TC again, the engine will now be able to find the create family match. 

Do you have any idea why this is happening, and how come that new patterns can influence the patterns that were already existing and found before?

Regards,
Milica

p.s. To be able to reproduce the error, please update Ibex from `https://emoflon.github.io/emoflon-ibex-democles/org.emoflon.ibex.tgg.ide.democles.updatesite/` and import the .psf file attached to this comment as `testProjectSet.zip`.  It will import all test projects correctly from the appropriate branch for this issue.

**Comment by anthonyanjorin** [comment]
So the situation is more or less the following:  
- Matches for a pattern P are found
- A new pattern Q is added that positively invokes P
- With both patterns P and Q no matches are found, neither for Q nor for P!

**Comment by anthonyanjorin** [comment]
If you run just this single problematic test you can see which matches are found in the console output (the structure of the rete network is also printed out)

**Comment by gervarro** [comment]
Just a short info first: adding new patterns to an already existing Rete network is not yet supported (even if the engine erroneously throws no exceptions). Rete network cannot be incrementally extended with new patterns. If you want to extend the Rete network, then you have to delete the old network (remove the `RetePatternMatcherModule` and detach the `NotificationProcessor` from the EMF model), create a new one from scratch (from the specification that contains more patterns) and feed the model again.

**Comment by anthonyanjorin** [comment]
Yes that’s fine.  With “adding” a pattern we mean creating everything from scratch.  So no addition of patterns at runtime.

**Comment by gervarro** [comment]
Hi,

I could not reproduce this error yet. I ran `testEmptyFamily` in the `testsuite.ibex.FamiliesToPersons_MA.cc.TestSimplePositive` class from the `cc-with-ma-rules-bug` branch. I got the following message as last line:

251 [main] DEBUG org.emoflon.ibex.tgg.operational.OperationalStrategy  - Successfully applied: Families2Persons__CC

Afterwards, I got an `UnsatisfiedLinkError`, because Gurobi is not installed on my computer. Shall I install it necessarily, or is it only used in the end?

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Gurobi is not needed, no need to install it.

Well the problem is that a match for `CreateFamily` is missing and not found.

If you however delete `MotherToFemale` then suddenly you'll get matches for both `Families2Persons` and `CreateFamily`.  So somehow an extra pattern is invalidating a match for another pattern which is rather unexpected.

**Comment by gervarro** [comment]
Hi,

there seems to be a bug in the specification of the `CreateFamily__CC_REFINEMENT_INVOCATIONS` pattern, namely, the parameters at the invocation of the `CreateFamily__SRC` pattern are swapped. The matcher for pattern `CreateFamily__SRC` produces matches in `family`, `familyReg` order, on the other hand, the pattern invocation uses a `familyReg`, `family` order. Could you please check this?

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Thanks, Greg!  I found a nasty bug in our pattern generation related again to hashmaps and unique keys.  This seems to have fixed the problem.
