### ISSUE TITLE
Create correct mapping of parameters for invoked marked patterns

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#4]
When there is more than one parameter in a pattern for which marked patterns must be invoked, there is a current bug that causes the same parameter to be invoked twice instead of once each (see the attached picture for parameter `m`).

The error is most probably in `IbexPattern::addVariableMapping` as HashMaps are used even though the keys (the marked patterns) are *not* always unique.

As a test to check if the problem is fixed, please see the patterns generated for `emoflon-ibex/org.emoflon.ibex.tgg.tests/testsuite2_familiestopersons`.

![i45 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/6302793/26927429-29e6e35c-4c52-11e7-849b-43a2fce88641.png)

**Comment by Arikae** [comment]
Done
