### ISSUE TITLE
Test deployed version with a fresh Eclipse

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#41]
I just deployed Ibex now with support for TGGs and the current state of the GT  tooling.

Please take a fresh installation of Eclipse and test:
- If you can install the current version of Ibex following our instructions
- If your wizards etc. work in this deployed state (sometimes there can be problems with paths and dependencies, etc)
- Check out all tests using our test PSF file and see if everything's green

**Comment by anthonyanjorin** [comment]
I just tried it out and can see that the icons for your wizards are missing.  You probably forgot to add them to the binary build (in the plugin.xml file).

**Comment by patrickrobrecht** [comment]
I found a small error in the test setup which I fixed: https://github.com/eMoflon/emoflon-ibex-tests/pull/44

In the fresh installation with the latest eMoflon::IBeX everything seems to be fine except the icons (which work well in the runtime-Eclipse started out of my dev-Eclipse).

**Comment by anthonyanjorin** [comment]
Yes, an installed Eclipse is always a bit different than one started from another running Eclipse.  Typical gotchas include problems with paths, resources that have not been packed explicitly into the jar, and dependencies that have not been declared properly.  These things tend to work in the runtime-Eclipse but then fail in a deployed setting.

**Comment by patrickrobrecht** [comment]
I located the bug in the  org.emoflon.ibex.gt.editor.ui plugin (`bin.includes` setting in the `build.properties`): see https://github.com/eMoflon/emoflon-ibex-ui/pull/44. If I replace the plugin's jar with a new one generated from the bugfix branch, the icons show up even in my fresh installation and everything works fine.

**Comment by patrickrobrecht** [comment]
The icons show up in the latest release, so I'll close this issue.
