### ISSUE TITLE
Invoking Democles from an installed plugin

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#54]
Hi Greg,

I'm still having problems getting this running for my student :(

Now I'm having:

```
java.lang.IllegalAccessError: tried to access field org.gervarro.democles.operation.emf.EMFNativeOperationBuilder.ecorePackage from class org.gervarro.democles.operation.emf.EMFBatchOperationBuilder
	at org.gervarro.democles.operation.emf.EMFBatchOperationBuilder.<init>(EMFBatchOperationBuilder.java:43)
```

I'm afraid Eclipse also has problems with protected variables (I have no other explanation at this point).

Could you consider adding a public getter perhaps?

Cheers,
Tony

**Comment by anthonyanjorin** [comment]
I'm not sure but perhaps this only works due to package visibility...  That would explain why Eclipse is having problems (has nothing to do with protected visibility).

**Comment by anthonyanjorin** [comment]
Hi Greg,

any chances of getting this fixed soon?  :)

Cheers and thanks,
Tony

**Comment by gervarro** [comment]
Hi Tony,

I am terribly sorry for this extreme delay in such an easy case. I already fixed it on my notebook while travelling on the train right after you contacted me. Afterwards, I forgot to do the rest and simply considered the case as completed in my mind. Thanks for the reminder.

The fix is available on the update site.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Thanks, Greg.  I’ll try it out ASAP :)

**Comment by anthonyanjorin** [comment]
Hi Greg,

I'm now getting:

```
java.lang.IllegalAccessError: tried to access method org.gervarro.democles.runtime.DeltaStore.clearContent()V from class org.gervarro.democles.runtime.HistoryBasedDeltaStore
	at org.gervarro.democles.runtime.HistoryBasedDeltaStore.cleanup(HistoryBasedDeltaStore.java:81)
	at org.gervarro.democles.runtime.IncrementalUpdateSession.call(IncrementalUpdateSession.java:151)
	at org.gervarro.democles.interpreter.incremental.rete.RetePatternMatcherModule.performIncrementalUpdates(RetePatternMatcherModule.java:115)
```

Cheers,
Tony

**Comment by gervarro** [comment]
Fix is available on the update site. Please keep in mind that such an error can unfortunately be fixed in such a trial and error manner. (The runtime OSGi environment might have become more strict in the latest Eclipse version.)

Bests
Greg

**Comment by anthonyanjorin** [comment]
No problem, Greg.  I just hope your deployment process is 100% automated so this ping-pong is not such a pain in the a** for you :)  I'll try it out right away.

**Comment by anthonyanjorin** [comment]
Yay!  This seems to be fixed now.
