### ISSUE TITLE
High memory consumption for models with many matches

### ISSUE THREAD

**Issue by RobinOppermann** [eMoflon/emoflon-ibex-democles#60]
I am using the consistency checker for a large model. During runtime I expect more than a million matches but I run into memory problems after about 200 000 matches. It seems the more matches are collected the more memory is needed even after the matches have been handled and applied. It seems to me that the information is kept and the memory is never freed again.
Profiling shows that the memory is hold by HashMap nodes and Object Arrays that seem to be referenced by democles' types. As I cannot find a place where the matches are kept within Ibex I guess they are still kept within Democles.
Is it necessary to keep the matches? Can the memory consumption somehow be improved? Or is it possible to "reset" the PatternMatcher at some point to free the memory?

**Comment by gervarro** [comment]
> Is it necessary to keep the matches?

An incremental pattern matcher (Democles) stores matches and updates the match set based on the changes in the model, and it has typically a large memory consumption. If you do not need incrementality in your setup, you can simply use the batch pattern matcher interpreter (re-runs pattern matching from scratch without storing any matches), or even generated code (also batch mode).

> Can the memory consumption somehow be improved?

Probably yes, but I should be able to understand what the exact problem is in your case.

> Or is it possible to "reset" the PatternMatcher at some point to free the memory?

If the pattern matcher is reset, then all the matches would be lost, consequently, the pattern matcher would not be incremental any more.

Note that the memory consumption in Democles at runtime is not only influenced by the number of partial and complete matches (that have to be stored in an incremental setup), but also by the size of the transaction. Democles needs temporary data structures that are used only during transaction processing. If you add 100 objects and links in one transaction, then the pattern matcher has temporarily a higher memory consumption, compared to the case, when you add the same objects and links in 100 separate transactions one by one. When the transaction processing is completed, the pattern matcher should have the same memory consumption in both cases (independently of whether the same number of objects and links were added in one or many transactions).
