### ISSUE TITLE
IBeX-GT: quickfix adds superfluous empty line

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-ibex-democles#68]
How to reproduce:
* Add a when clause to an abstract rule (e.g., pushBlock in handbook)
* Accept quickfix that removes the when clause
* A new superfluous line is inserted

**Comment by patrickrobrecht** [comment]
The same happens for some other quickfixes, but I've no idea why this is happening and how to fix this. Any idea on this?

**Comment by patrickrobrecht** [comment]
Closed in favor of issue https://github.com/eMoflon/emoflon-ibex-ui/issues/107
