### ISSUE TITLE
CC: Return information about success of the check

### ISSUE THREAD

**Issue by FStolte** [eMoflon/emoflon-ibex-democles#7]
Hi all,

I want to write some tests for the CC, and for that it would be quite useful if we could directly get output about whether the models are consistent or not.

Thanks,
Florian

**Comment by erhanleblebici** [comment]
I have implemented some cc-features including a boolean flag for consistency.
You can do the following things with cc after execting its run-method (method names are hopefully self-explaining). Do not hesitate to contact me for questions and feedback

`boolean consistent = cc.modelsAreConsistent();
		    String consistencyReport = cc.generateConsistencyReport();
		    Collection<EObject> inconsistentSrcNodes = cc.getInconsistentSrcNodes();
		    Collection<RuntimeEdge> inconsistentSrcEdges = cc.getInconsistentSrcEdges();
		    Collection<EObject> inconsistentTrgNodes = cc.getInconsistentSrcNodes();
		    Collection<RuntimeEdge> inconsistentTrgEdges = cc.getInconsistentSrcEdges();`
